<a href="https://colab.research.google.com/github/Seriphap/Exercise_LoadBigDataset/blob/main/HW_3_2_LoadingBigDataset_6710422002.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Download CSV file into Dataframe

In [ ]:
# @title
!pip install gdown

Requirement already satisfied: gdown in /usr/local/lib/python3.11/dist-packages (5.2.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from gdown) (4.13.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from gdown) (3.17.0)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.11/dist-packages (from gdown) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from gdown) (4.67.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->gdown) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->gdown) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (2025.1.31)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.11/dist-packages (from requests[socks]->gdown) (1.7.1)

In [ ]:
# @title
import dask.dataframe as dd
import gdown

file_id = '1njGRC9gjmnbi9qGLmzRQj4MyMyPDHp1h'
url = f'https://drive.google.com/uc?id={file_id}'

# Download the file
gdown.download(url, '/content/downloaded_file.csv', quiet=False)

# Read CSV with Dask
df = dd.read_csv('/content/downloaded_file.csv')

Downloading...
From (original): https://drive.google.com/uc?id=1njGRC9gjmnbi9qGLmzRQj4MyMyPDHp1h
From (redirected): https://drive.google.com/uc?id=1njGRC9gjmnbi9qGLmzRQj4MyMyPDHp1h&confirm=t&uuid=8fe817ec-891b-4d4c-8505-81b8b32f7d13
To: /content/downloaded_file.csv
100%|██████████| 3.04G/3.04G [00:33<00:00, 90.2MB/s]

# 2. Show the data information

In [ ]:
# @title
display(df.info())
#display(df.columns)
display(df.dtypes) # Display column data types (metadata)

<class 'dask.dataframe.core.DataFrame'>
Columns: 19 entries, case_id to subjectroles_name_838M
dtypes: float64(10), int64(3), string(6)

None

case_id                                      int64
collater_typofvalofguarant_298M    string[pyarrow]
collater_typofvalofguarant_407M    string[pyarrow]
collater_valueofguarantee_1124L            float64
collater_valueofguarantee_876L             float64
collaterals_typeofguarante_359M    string[pyarrow]
collaterals_typeofguarante_669M    string[pyarrow]
num_group1                                   int64
num_group2                                   int64
pmts_dpd_1073P                             float64
pmts_dpd_303P                              float64
pmts_month_158T                            float64
pmts_month_706T                            float64
pmts_overdue_1140A                         float64
pmts_overdue_1152A                         float64
pmts_year_1139T                            float64
pmts_year_507T                             float64
subjectroles_name_541M             string[pyarrow]
subjectroles_name_838M             string[pyarrow]
dtype: object

# Example Data (10 Rows)

In [ ]:
# @title
display(df.head(10))
#display(df.tail())#last rows from the last partition
num_rows = len(df.compute())
print(f"Number of rows: {num_rows}")

,case_id,collater_typofvalofguarant_298M,collater_typofvalofguarant_407M,collater_valueofguarantee_1124L,collater_valueofguarantee_876L,collaterals_typeofguarante_359M,collaterals_typeofguarante_669M,num_group1,num_group2,pmts_dpd_1073P,pmts_dpd_303P,pmts_month_158T,pmts_month_706T,pmts_overdue_1140A,pmts_overdue_1152A,pmts_year_1139T,pmts_year_507T,subjectroles_name_541M,subjectroles_name_838M
0,36830,9a0c095e,8fd95e4b,0.0,0.0,3cbe86ba,c7a5ad39,0,0,NaN,NaN,2.0,2.0,NaN,NaN,2017.0,2013.0,ab3c25cf,ab3c25cf
1,36830,8fd95e4b,8fd95e4b,0.0,0.0,c7a5ad39,c7a5ad39,1,0,NaN,NaN,2.0,2.0,NaN,NaN,2017.0,2016.0,ab3c25cf,ab3c25cf
2,36830,9a0c095e,a55475b1,0.0,NaN,a55475b1,c7a5ad39,2,0,NaN,NaN,2.0,NaN,NaN,NaN,2018.0,NaN,a55475b1,ab3c25cf
3,36830,8fd95e4b,a55475b1,0.0,NaN,a55475b1,c7a5ad39,3,0,NaN,NaN,2.0,NaN,NaN,NaN,2018.0,NaN,a55475b1,ab3c25cf
4,36830,9a0c095e,a55475b1,0.0,NaN,a55475b1,c7a5ad39,4,0,NaN,NaN,2.0,NaN,NaN,NaN,2018.0,NaN,a55475b1,ab3c25cf
5,36830,a55475b1,a55475b1,NaN,NaN,a55475b1,a55475b1,0,1,NaN,0.0,3.0,3.0,NaN,0.0,2017.0,2013.0,a55475b1,a55475b1
6,36830,a55475b1,a55475b1,NaN,NaN,a55475b1,a55475b1,0,2,NaN,0.0,4.0,4.0,NaN,0.0,2017.0,2013.0,a55475b1,a55475b1
7,36830,a55475b1,a55475b1,NaN,NaN,a55475b1,a55475b1,0,3,NaN,0.0,5.0,5.0,NaN,0.0,2017.0,2013.0,a55475b1,a55475b1
8,36830,a55475b1,a55475b1,NaN,NaN,a55475b1,a55475b1,0,4,NaN,0.0,6.0,6.0,NaN,0.0,2017.0,2013.0,a55475b1,a55475b1
9,36830,a55475b1,a55475b1,NaN,NaN,a55475b1,a55475b1,0,5,NaN,0.0,7.0,7.0,NaN,0.0,2017.0,2013.0,a55475b1,a55475b1

Number of rows: 33053760

# Summary Statistics of Data

In [ ]:
# @title
#Show summary statistics (like describe in pandas)
print("\nSummary statistics:")
display(df.describe().compute())  # Trigger computation with compute()

Summary statistics:

,case_id,collater_valueofguarantee_1124L,collater_valueofguarantee_876L,num_group1,num_group2,pmts_dpd_1073P,pmts_dpd_303P,pmts_month_158T,pmts_month_706T,pmts_overdue_1140A,pmts_overdue_1152A,pmts_year_1139T,pmts_year_507T
count,3.305376e+07,4.701760e+05,1.327778e+06,3.305376e+07,3.305376e+07,5.932387e+06,1.436250e+07,9.249528e+06,3.043391e+07,5.962480e+06,1.437950e+07,9.249528e+06,3.043391e+07
mean,1.457855e+06,1.044418e+07,4.160212e+06,4.701797e+00,1.320155e+01,1.262911e+01,5.452470e+01,6.500000e+00,6.500000e+00,2.047064e+03,4.190193e+03,2.018580e+03,2.014328e+03
std,6.574535e+05,2.797464e+08,1.537820e+08,6.427977e+00,9.278773e+00,1.430431e+02,2.747676e+02,3.452053e+00,3.452053e+00,2.658240e+05,1.053404e+05,7.459096e-01,3.932180e+00
min,3.683000e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-3.000000e+01,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,2.016000e+03,2.001000e+03
25%,9.153400e+05,0.000000e+00,0.000000e+00,1.000000e+00,6.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00,4.000000e+00,0.000000e+00,0.000000e+00,2.018000e+03,2.012000e+03
50%,1.665535e+06,0.000000e+00,0.000000e+00,4.000000e+00,1.200000e+01,0.000000e+00,0.000000e+00,7.000000e+00,7.000000e+00,0.000000e+00,0.000000e+00,2.019000e+03,2.016000e+03
75%,1.715827e+06,0.000000e+00,0.000000e+00,9.000000e+00,2.100000e+01,0.000000e+00,0.000000e+00,1.000000e+01,1.000000e+01,0.000000e+00,0.000000e+00,2.019000e+03,2.018000e+03
max,2.658153e+06,1.875996e+10,1.758996e+10,2.710000e+02,1.000000e+02,4.595000e+03,1.170000e+05,1.200000e+01,1.200000e+01,4.019803e+08,5.090647e+07,2.021000e+03,2.021000e+03